moviesite/movie/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('news/', news, name='news'),
    path('comsoon/', comsoon, name='comsoon'),
    path('/<str:slug>/', GetPost.as_view(), name='post'),
    path('category/<str:slug>/', PostsByCategory.as_view(), name='category'),
    path('search/', Search.as_view(), name='search'),
    path("review/<int:pk>/", AddReview.as_view(), name="add_review"),
]

moviesite/moviesite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesite/movie/models.py
from distutils.command.upload import upload
from pyexpat import model
from tabnanny import verbose
from unicodedata import category
from django import views
from django.db import models
from django.urls import reverse

'''

Category
=========
title, slug

Tag
========
title, slug

Post
=======
Title, logo, slug, content, data_ad, views, category, tags



'''


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Категория(ю)'
        verbose_name_plural = 'Категории'
        ordering = ['title']


# class Tag(models.Model):
#     title = models.CharField(max_length=50)
#     slug = models.SlugField(max_length=50, verbose_name='Url', unique=True)

#     def __str__(self):
#         return self.title

#     class Meta:
#         ordering = ['title']


class Quality(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quality', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Качество'
        verbose_name_plural = 'Качество'
        ordering = ['title']


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    logo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, verbose_name='Фото')
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)

    content = models.CharField(max_length=5000, verbose_name='Описание')
    urlmov = models.CharField(max_length=500, verbose_name='Ссылка на видео')
    data_ad = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='movies', verbose_name='Категория')
    # tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    released = models.CharField(max_length=15, verbose_name='Год выхода', blank=True)
    director = models.CharField(max_length=50, verbose_name='Режиссер', blank=True)
    side = models.CharField(max_length=50, verbose_name='Страна', null=True, blank=True)
    actors = models.CharField(max_length=5000, verbose_name='Актеры', null=True, blank=True)
    genre = models.CharField(max_length=3000, verbose_name='Жанр', null=True, blank=True)
    translation = models.CharField(max_length=3000, verbose_name='Перевод', null=True, blank=True)
    quality = models.ForeignKey(Quality, on_delete=models.PROTECT, related_name='movies',
                                verbose_name='Качество', blank=True)
    rateKP = models.CharField(max_length=3000, verbose_name='Рейтинг КП', null=True, blank=True)
    rateIMDB = models.CharField(max_length=3000, verbose_name='Рейтинг IMDB', null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-data_ad']


class Reviews(models.Model):
    """Отзывы"""
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Post, verbose_name="фильм", on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        ordering = ['-pub_date']

moviesite/movie/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ("name", "text")

moviesite/movie/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import *
from django.db.models import F
from django.views.generic.base import View
from .forms import ReviewForm

class Home(ListView):
    model = Post
    template_name = 'movie/index.html'
    context_object_name = 'posts'
    paginate_by = 50

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Фильм'
        return context


class PostsByCategory(ListView):
    template_name = 'movie/category.html'
    context_object_name = 'posts'    
    paginate_by = 50
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        return context    


class GetPost(DetailView):
    model = Post
    template_name = 'movie/single.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()
        return context 


class Search(ListView):
    template_name = 'movie/search.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['s'] = f"s={self.request.GET.get('s')}"
        return context


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Post.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


def news(request):
    return render(request, 'movie/news.html')


def comsoon(request):
    return render(request, 'movie/comsoon.html')

# def get_post(request, slug):
#     return render(request, 'movie/index.html')

moviesite/movie/templates/movie/category.html
{% extends 'base.html' %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}

<div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h1>{{ title }}</h1>
          <!-- <p class="text-right"><a href="#">See all</a></p> -->
        </div>
        {% for post in posts %}
        <div class="movie">
          <div class="movie-image"> <span class="play"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a><span class="name">{{ post.title.url }}</span></span> <a href="#">
            
            <img src="{{ post.logo.url }}" alt="" /></a> </div>
          <div class="rating">
            <h4>{{ post.title }}</h4>
            <span class="comments"></span> </div>
        </div>
        {% endfor %}
        <div class="cl">&nbsp;</div>
      </div>
    </div>

    <!-- {% if page_obj.has_other_pages %}
    <div class="pagination">
      <div class="nav-links">

        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.numbers == p %}
            <span class="page-numbers current">{{ p }}</span>
            {% else %}
            <a class="page-numbers" href="?page={{ p }}">{{ p }}</a>
            {% endif %}
        {% endfor %}

        <span class="page-numbers current">1</span>
        <a class="page-numbers" href="#">2</a>
        <a class="page-numbers" href="#"><i class="fa fa-angle-right"></i></a>

      </div>
    </div>
    {% endif %} -->

    <div class="cl">&nbsp;</div>
  </div>

{% endblock %}

moviesite/movie/templates/movie/comsoon.html
{% extends 'base.html' %}
{% block content %}


<div class="head">
    <h3>COMING SOON<strong>!</strong></h3>
    <p class="text-right"><a href="#">See all</a></p>
</div>
<div class="content">
    <h4>The Princess and the Frog </h4>
    <a href="#"><img src="css/images/coming-soon1.jpg" alt="" /></a>
    <p>Walt Disney Animation Studios presents the musical &quot;The Princess and the Frog,&quot; an animated comedy set in the great city of New Orleans...</p>
    <a href="#">Read more</a> </div>
<div class="cl">&nbsp;</div>
<div class="content">
    <h4>The Princess and the Frog </h4>
    <a href="#"><img src="css/images/coming-soon2.jpg" alt="" /></a>
    <p>Walt Disney Animation Studios presents the musical &quot;The Princess and the Frog,&quot; an animated comedy set in the great city of New Orleans...</p>
    <a href="#">Read more</a> </div>
</div>

{% endblock content %}

moviesite/movie/templates/movie/index.html
{% extends 'base.html' %}

{% block title %}{{ title }} :: {{ block.super }}{% endblock %}

{% block content %}

<div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h1>Фильмы Онлайн</h1>
          <!-- <p class="text-right"><a href="#">See all</a></p> -->
        </div>
        {% for post in posts %}
        <div class="movie">
          <div class="movie-image"> <span class="play"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a><span class="name">{{ post.title.url }}</span></span> <a href="#">
            
            <img src="{{ post.logo.url }}" alt="" /></a> </div>
          <div class="rating">
            <h4>{{ post.title }}</h4>
            <span class="comments"></span> </div>
        </div>
        {% endfor %}
        <div class="cl">&nbsp;</div>
      </div>
    </div>

    <!-- {% if page_obj.has_other_pages %}
    <div class="pagination">
      <div class="nav-links">

        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.numbers == p %}
            <span class="page-numbers current">{{ p }}</span>
            {% else %}
            <a class="page-numbers" href="?page={{ p }}">{{ p }}</a>
            {% endif %}
        {% endfor %}

        <span class="page-numbers current">1</span>
        <a class="page-numbers" href="#">2</a>
        <a class="page-numbers" href="#"><i class="fa fa-angle-right"></i></a>

      </div>
    </div>
    {% endif %} -->

    <div class="cl">&nbsp;</div>
  </div>

{% endblock %}

moviesite/movie/templates/movie/menu_tpl.html
<div class="menu">
  <div id="sub-navigation">
      <div>
        <ul>
          <li><a href="{% url 'home' %}">Все</a></li>
          {% for item in categories %}
          <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <div id="search">

          <label for="search-field">Поиск</label>
          <form action="{% url 'search' %}" method="get">
              <input type="text" name="s" id="search-field" class="blink search-field"  />
              <input type="submit" value="GO" class="search-button" />
          </form>

      </div>
  </div>
</div>

moviesite/movie/templates/movie/news.html
{% extends 'base.html' %}
{% block title %}{{ title }} :: {{ block.super }}{% endblock %}
{% block content %}


<div class="head">
    <h1>Новости</h1>    
</div>
<div class="content">
    <p class="date">12.04.09</p>
    <h4>Disney's A Christmas Carol</h4>
    <p>&quot;Disney's A Christmas Carol,&quot; a multi-sensory thrill ride re-envisioned by Academy Award&reg;-winning filmmaker Robert Zemeckis, captures... </p>
    <a href="#">Read more</a> </div>
<div class="content">
    <p class="date">11.04.09</p>
    <h4>Where the Wild Things Are</h4>
    <p>Innovative director Spike Jonze collaborates with celebrated author Maurice Sendak to bring one of the most beloved books of all time to the big screen in &quot;Where the Wild Things Are,&quot;...</p>
    <a href="#">Read more</a> </div>
<div class="content">
    <p class="date">10.04.09</p>
    <h4>The Box</h4>
    <p>Norma and Arthur Lewis are a suburban couple with a young child who receive an anonymous gift bearing fatal and irrevocable consequences.</p>
    <a href="#">Read more</a> </div>
</div>

{% endblock content %}

moviesite/movie/templates/movie/search.html
{% extends 'base.html' %}

{% block title %}Поиск :: {{ block.super }}{% endblock %}

{% block content %}

<div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h1>Результаты поиска</h1>
          <!-- <p class="text-right"><a href="#">See all</a></p> -->
        </div>
        {% for post in posts %}
        <div class="movie">
          <div class="movie-image"> <span class="play"><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a><span class="name">{{ post.title.url }}</span></span> <a href="#">
            
            <img src="{{ post.logo.url }}" alt="" /></a> </div>
          <div class="rating">
            <h4>{{ post.title }}</h4>
            <span class="comments"></span> </div>
        </div>
        {% endfor %}
        <div class="cl">&nbsp;</div>
      </div>
    </div>
    <!-- {% if page_obj.has_other_pages %}
    <div class="pagination">
      <div class="nav-links">

        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.numbers == p %}
            <span class="page-numbers current">{{ p }}</span>
            {% else %}
            <a class="page-numbers" href="?page={{ p }}">{{ p }}</a>
            {% endif %}
        {% endfor %}

        <span class="page-numbers current">1</span>
        <a class="page-numbers" href="#">2</a>
        <a class="page-numbers" href="#"><i class="fa fa-angle-right"></i></a>

      </div>
    </div>
    {% endif %} -->

    <div class="cl">&nbsp;</div>
  </div>

{% endblock %}

moviesite/movie/templates/movie/single.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} :: {{ block.super }}{% endblock %}

{% block content %}

<div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h1>{{ post.title }}</h1>


          <table class="iksweb">
              <tbody>
                  <tr>
                      <td rowspan="2" id="piccol"><img src="{{ post.logo.url }}" alt="" /></td>
                      <td><h3>{{ post.content }}</h3></td>
                  </tr>
                  <tr id="textcol">
                      <td>
                          <h3><i><font color="#fa8e47">Год выхода:</font></i> {{ post.released }}</h3>
                          {% if post.director %}
                          <h3><i><font color="#fa8e47">Режиссер:</font></i> {{ post.director }}</h3>
                          {% endif %}
                          {% if post.side %}
                          <h3><i><font color="#fa8e47">Страна:</font></i> {{ post.side }}</h3>
                          {% endif %}
                          {% if post.actors %}
                          <h3><i><font color="#fa8e47">Актеры:</font></i> {{ post.actors }}</h3>
                          {% endif %}
                          {% if post.genre %}
                          <h3><i><font color="#fa8e47">Жанр:</font></i> {{ post.genre }}</h3>
                          {% endif %}
                          {% if post.rateKP %}
                          <h3><i><font color="#fa8e47">Рейтинг Кинопоиск:</font></i> {{ post.rateKP }}</h3>
                          {% endif %}
                          {% if post.rateIMDB %}
                            <h3><i><font color="#fa8e47">Рейтинг IMDB:</font></i> {{ post.rateIMDB }}</h3>
                          {% endif %}
                          {% if post.translation %}
                          <h3><i><font color="#fa8e47">Перевод:</font></i> {{ post.translation }}</h3>
                          {% endif %}
                          {% if post.quality %}
                          <h3><i><font color="#fa8e47">Качество:</font></i> {{ post.quality }}</h3>
                          {% endif %}
                  </tr>
              </tbody>
          </table>

          <div class="tabs-b video-box visible">
            <h1 align="center">Смотреть {{ post.title }} в HD 720-1080 хорошем качестве</h1>
            <iframe width="960" height="600" src="{{ post.urlmov }}" frameborder="0" allowfullscreen=""></iframe>
            </div>
          <div class="row" align="left">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h4 class="editContent" style="outline: none; cursor: inherit;">
                                    Оставить отзыв</h4>
                    <form action="{% url 'add_review' post.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <p>
                                    Ваше имя *
                                </p>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>

                        </div>
                        <div class="form-group editContent">
                            <p>
                                Ваш комментарий *
                            </p>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>

                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить отзыв
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
          <!-- <p class="text-right"><a href="#">See all</a></p> -->
        </div>

        <div class="cl">&nbsp;</div>
      </div>
    </div>

                <h4>Отзывы:</h4>

                {% for review in post.reviews_set.all %}
            <div class="media py-5" align="left">
                <div class="media-body mt-4">

                    <h4 class="mt-0 editContent">
                        Имя: {{ review.name }}
                    </h4>

                    <p class="mt-2 editContent">
                        Комментарий: {{ review.text }}
                    </p>
                    <p class="mt-2 editContent">
                        {{ review.pub_date }}
                    </p>
                </div>
            </div>
        {% endfor %}




    <div class="cl">&nbsp;</div>
  </div>

{% endblock %}

moviesite/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load menu %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{% block title %}MOVIE HD{% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="/">MovieHunter</a></h1>
    <div id="navigation">
      <ul>
        <li><a class="active" href="/">Главная</a></li>
        <li><a href="/news/">Новости</a></li>
        <li><a href="/comsoon/">Скоро выйдут</a></li>
      </ul>
    </div>

    {% show_menu %}
  </div>
  <div id="main">          
    {% block content %}
    {% endblock content %}    
  </div>    
  <div id="footer">
    <p class="lf">Copyright &copy; 2022 <a href="#">MOVIE HD</a> - All Rights Reserved</p>
    <!-- <div style="clear:both;"></div> -->
  </div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>